version: '3.8'

services:
  database_express_mysql:
    hostname: database_express_mysql
    container_name: database_mext_mysql
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'MYSQL_PWD=${MYSQL_PASSWORD} mysqladmin ping -h localhost',
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    expose:
      - ${MYSQL_PORT}
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - my-network

  express-back:
    container_name: express-back
    hostname: express-back
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      MYSQL_HOST: host.docker.internal
    # command: sh -c "node ace migration:run"
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - database_express_mysql
    networks:
      - my-network

volumes:
  my-db:
    driver: local

networks:
  my-network:
    driver: bridge
